version: '3'

services:
  app:
    image: pgbouncersample/app
    links:
      - app-postgres-db:app-postgres-db
    ports:
      - 80:80
    environment:
      - UploadUrl=Uploads
      - BackendRoot=https://localhost
      - DefConnStr=SERVER=app-postgres-db;User ID=flexberryuser;Password=jhv;Port=5432;database=appdb;
      - AuditConnStr=SERVER=app-postgres-db;User ID=flexberryuser;Password=jhv;Port=5432;database=auditdb;
      - SecurityConnString=SERVER=app-postgres-db;User ID=flexberryuser;Password=jhv;Port=5432;database=securitydb;

  app-postgres-db:
    image: pgbouncersample/postgre-sql
    volumes:
      - DB:/var/lib/pgsql/data/
    ports:
      - 5432:5432
volumes:
  DB:
