CREATE TABLE Brand (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NULL,
 CreateTime TIMESTAMP(3) NULL,
 Creator VARCHAR(255) NULL,
 EditTime TIMESTAMP(3) NULL,
 Editor VARCHAR(255) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Car (
 primaryKey UUID NOT NULL,
 CarNumber VARCHAR(255) NOT NULL,
 CarBody VARCHAR(9) NULL,
 CarDate TIMESTAMP(3) NOT NULL,
 CreateTime TIMESTAMP(3) NULL,
 Creator VARCHAR(255) NULL,
 EditTime TIMESTAMP(3) NULL,
 Editor VARCHAR(255) NULL,
 Brand_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE ProducingCountry (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NULL,
 CreateTime TIMESTAMP(3) NULL,
 Creator VARCHAR(255) NULL,
 EditTime TIMESTAMP(3) NULL,
 Editor VARCHAR(255) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE UserReport (
 primaryKey UUID NOT NULL,
 UserName VARCHAR(255) NOT NULL,
 UserEmail VARCHAR(255) NULL,
 ReportId UUID NOT NULL,
 ReportTaskStartTime TIMESTAMP(3) NULL,
 Status VARCHAR(10) NULL,
 File TEXT NULL,
 CreateTime TIMESTAMP(3) NULL,
 Creator VARCHAR(255) NULL,
 EditTime TIMESTAMP(3) NULL,
 Editor VARCHAR(255) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE SparePart (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NULL,
 Quantity INT NULL,
 Used BOOLEAN NULL,
 CreateTime TIMESTAMP(3) NULL,
 Creator VARCHAR(255) NULL,
 EditTime TIMESTAMP(3) NULL,
 Editor VARCHAR(255) NULL,
 ProducingCountry_m0 UUID NULL,
 Car_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


 CREATE TABLE ApplicationLog (
 primaryKey UUID NOT NULL,
 Category VARCHAR(64) NULL,
 EventId INT NULL,
 Priority INT NULL,
 Severity VARCHAR(32) NULL,
 Title VARCHAR(256) NULL,
 Timestamp TIMESTAMP(3) NULL,
 MachineName VARCHAR(32) NULL,
 AppDomainName VARCHAR(512) NULL,
 ProcessId VARCHAR(256) NULL,
 ProcessName VARCHAR(512) NULL,
 ThreadName VARCHAR(512) NULL,
 Win32ThreadId VARCHAR(128) NULL,
 Message VARCHAR(2500) NULL,
 FormattedMessage TEXT NULL,
 PRIMARY KEY (primaryKey));

 ALTER TABLE Car ADD CONSTRAINT FK486d49af379b9b088fb8421790708fa4f1b0632a FOREIGN KEY (Brand_m0) REFERENCES Brand; 
CREATE INDEX Index486d49af379b9b088fb8421790708fa4f1b0632a on Car (Brand_m0); 

 ALTER TABLE SparePart ADD CONSTRAINT FKe889cc1c7c4771ab78c1d6033cf588d71eff082a FOREIGN KEY (ProducingCountry_m0) REFERENCES ProducingCountry; 
CREATE INDEX Indexe889cc1c7c4771ab78c1d6033cf588d71eff082a on SparePart (ProducingCountry_m0); 

 ALTER TABLE SparePart ADD CONSTRAINT FK9060f078b443dafa963f06c5dc6cd1c6301e73bd FOREIGN KEY (Car_m0) REFERENCES Car; 
CREATE INDEX Index9060f078b443dafa963f06c5dc6cd1c6301e73bd on SparePart (Car_m0);