//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.PgBouncerSample
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Car type.
    /// </summary>
    // *** Start programmer edit section *** (CarType CustomAttributes)

    // *** End programmer edit section *** (CarType CustomAttributes)
    public enum CarType
    {
        
        // *** Start programmer edit section *** (CarType.Coupe CustomAttributes)

        // *** End programmer edit section *** (CarType.Coupe CustomAttributes)
        Coupe,
        
        // *** Start programmer edit section *** (CarType.Sedan CustomAttributes)

        // *** End programmer edit section *** (CarType.Sedan CustomAttributes)
        Sedan,
        
        // *** Start programmer edit section *** (CarType.Crossover CustomAttributes)

        // *** End programmer edit section *** (CarType.Crossover CustomAttributes)
        Crossover,
    }
}
