//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.PgBouncerSample
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Report status type.
    /// </summary>
    // *** Start programmer edit section *** (ReportStatusType CustomAttributes)

    // *** End programmer edit section *** (ReportStatusType CustomAttributes)
    public enum ReportStatusType
    {
        
        // *** Start programmer edit section *** (ReportStatusType.InProgress CustomAttributes)

        // *** End programmer edit section *** (ReportStatusType.InProgress CustomAttributes)
        InProgress,
        
        // *** Start programmer edit section *** (ReportStatusType.Unexecuted CustomAttributes)

        // *** End programmer edit section *** (ReportStatusType.Unexecuted CustomAttributes)
        Unexecuted,
        
        // *** Start programmer edit section *** (ReportStatusType.Executed CustomAttributes)

        // *** End programmer edit section *** (ReportStatusType.Executed CustomAttributes)
        Executed,
    }
}
