//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.PgBouncerSample
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    using ICSSoft.STORMNET.Business.Audit.Objects;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Spare part.
    /// </summary>
    // *** Start programmer edit section *** (SparePart CustomAttributes)

    // *** End programmer edit section *** (SparePart CustomAttributes)
    [AutoAltered()]
    [Caption("Spare part")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("AuditView", new string[] {
            "Name as \'Name\'",
            "Quantity as \'Quantity\'",
            "Used as \'Used\'",
            "ProducingCountry as \'Producing country\'",
            "ProducingCountry.Name as \'Name\'"}, Hidden=new string[] {
            "ProducingCountry.Name"})]
    [MasterViewDefineAttribute("AuditView", "ProducingCountry", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("SparePartE", new string[] {
            "Name as \'Name\'",
            "Quantity as \'Quantity\'",
            "Used as \'Used\'",
            "ProducingCountry as \'Producing country\'",
            "ProducingCountry.Name as \'Name\'"}, Hidden=new string[] {
            "ProducingCountry.Name"})]
    [MasterViewDefineAttribute("SparePartE", "ProducingCountry", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    public class SparePart : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields
    {
        
        private string fName;
        
        private int fQuantity;
        
        private bool fUsed = false;
        
        private System.Nullable<System.DateTime> fCreateTime;
        
        private string fCreator;
        
        private System.Nullable<System.DateTime> fEditTime;
        
        private string fEditor;
        
        private IIS.PgBouncerSample.ProducingCountry fProducingCountry;
        
        private IIS.PgBouncerSample.Car fCar;
        
        // *** Start programmer edit section *** (SparePart CustomMembers)

        // *** End programmer edit section *** (SparePart CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (SparePart.Name CustomAttributes)

        // *** End programmer edit section *** (SparePart.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (SparePart.Name Get start)

                // *** End programmer edit section *** (SparePart.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (SparePart.Name Get end)

                // *** End programmer edit section *** (SparePart.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SparePart.Name Set start)

                // *** End programmer edit section *** (SparePart.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (SparePart.Name Set end)

                // *** End programmer edit section *** (SparePart.Name Set end)
            }
        }
        
        /// <summary>
        /// Quantity.
        /// </summary>
        // *** Start programmer edit section *** (SparePart.Quantity CustomAttributes)

        // *** End programmer edit section *** (SparePart.Quantity CustomAttributes)
        public virtual int Quantity
        {
            get
            {
                // *** Start programmer edit section *** (SparePart.Quantity Get start)

                // *** End programmer edit section *** (SparePart.Quantity Get start)
                int result = this.fQuantity;
                // *** Start programmer edit section *** (SparePart.Quantity Get end)

                // *** End programmer edit section *** (SparePart.Quantity Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SparePart.Quantity Set start)

                // *** End programmer edit section *** (SparePart.Quantity Set start)
                this.fQuantity = value;
                // *** Start programmer edit section *** (SparePart.Quantity Set end)

                // *** End programmer edit section *** (SparePart.Quantity Set end)
            }
        }
        
        /// <summary>
        /// Used.
        /// </summary>
        // *** Start programmer edit section *** (SparePart.Used CustomAttributes)

        // *** End programmer edit section *** (SparePart.Used CustomAttributes)
        public virtual bool Used
        {
            get
            {
                // *** Start programmer edit section *** (SparePart.Used Get start)

                // *** End programmer edit section *** (SparePart.Used Get start)
                bool result = this.fUsed;
                // *** Start programmer edit section *** (SparePart.Used Get end)

                // *** End programmer edit section *** (SparePart.Used Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SparePart.Used Set start)

                // *** End programmer edit section *** (SparePart.Used Set start)
                this.fUsed = value;
                // *** Start programmer edit section *** (SparePart.Used Set end)

                // *** End programmer edit section *** (SparePart.Used Set end)
            }
        }
        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (SparePart.CreateTime CustomAttributes)

        // *** End programmer edit section *** (SparePart.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (SparePart.CreateTime Get start)

                // *** End programmer edit section *** (SparePart.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (SparePart.CreateTime Get end)

                // *** End programmer edit section *** (SparePart.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SparePart.CreateTime Set start)

                // *** End programmer edit section *** (SparePart.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (SparePart.CreateTime Set end)

                // *** End programmer edit section *** (SparePart.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (SparePart.Creator CustomAttributes)

        // *** End programmer edit section *** (SparePart.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (SparePart.Creator Get start)

                // *** End programmer edit section *** (SparePart.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (SparePart.Creator Get end)

                // *** End programmer edit section *** (SparePart.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SparePart.Creator Set start)

                // *** End programmer edit section *** (SparePart.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (SparePart.Creator Set end)

                // *** End programmer edit section *** (SparePart.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (SparePart.EditTime CustomAttributes)

        // *** End programmer edit section *** (SparePart.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (SparePart.EditTime Get start)

                // *** End programmer edit section *** (SparePart.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (SparePart.EditTime Get end)

                // *** End programmer edit section *** (SparePart.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SparePart.EditTime Set start)

                // *** End programmer edit section *** (SparePart.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (SparePart.EditTime Set end)

                // *** End programmer edit section *** (SparePart.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (SparePart.Editor CustomAttributes)

        // *** End programmer edit section *** (SparePart.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (SparePart.Editor Get start)

                // *** End programmer edit section *** (SparePart.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (SparePart.Editor Get end)

                // *** End programmer edit section *** (SparePart.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SparePart.Editor Set start)

                // *** End programmer edit section *** (SparePart.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (SparePart.Editor Set end)

                // *** End programmer edit section *** (SparePart.Editor Set end)
            }
        }
        
        /// <summary>
        /// Spare part.
        /// </summary>
        // *** Start programmer edit section *** (SparePart.ProducingCountry CustomAttributes)

        // *** End programmer edit section *** (SparePart.ProducingCountry CustomAttributes)
        public virtual IIS.PgBouncerSample.ProducingCountry ProducingCountry
        {
            get
            {
                // *** Start programmer edit section *** (SparePart.ProducingCountry Get start)

                // *** End programmer edit section *** (SparePart.ProducingCountry Get start)
                IIS.PgBouncerSample.ProducingCountry result = this.fProducingCountry;
                // *** Start programmer edit section *** (SparePart.ProducingCountry Get end)

                // *** End programmer edit section *** (SparePart.ProducingCountry Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SparePart.ProducingCountry Set start)

                // *** End programmer edit section *** (SparePart.ProducingCountry Set start)
                this.fProducingCountry = value;
                // *** Start programmer edit section *** (SparePart.ProducingCountry Set end)

                // *** End programmer edit section *** (SparePart.ProducingCountry Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.PgBouncerSample.Car.
        /// </summary>
        // *** Start programmer edit section *** (SparePart.Car CustomAttributes)

        // *** End programmer edit section *** (SparePart.Car CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.PgBouncerSample.Car Car
        {
            get
            {
                // *** Start programmer edit section *** (SparePart.Car Get start)

                // *** End programmer edit section *** (SparePart.Car Get start)
                IIS.PgBouncerSample.Car result = this.fCar;
                // *** Start programmer edit section *** (SparePart.Car Get end)

                // *** End programmer edit section *** (SparePart.Car Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SparePart.Car Set start)

                // *** End programmer edit section *** (SparePart.Car Set start)
                this.fCar = value;
                // *** Start programmer edit section *** (SparePart.Car Set end)

                // *** End programmer edit section *** (SparePart.Car Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(IIS.PgBouncerSample.SparePart));
                }
            }
            
            /// <summary>
            /// "SparePartE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SparePartE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SparePartE", typeof(IIS.PgBouncerSample.SparePart));
                }
            }
        }
        
        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {
            
            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;
            
            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;
            
            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";
            
            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";
            
            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;
            
            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;
            
            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;
            
            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;
            
            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;
            
            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }
    
    /// <summary>
    /// Detail array of SparePart.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfSparePart CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfSparePart CustomAttributes)
    public class DetailArrayOfSparePart : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.PgBouncerSample.DetailArrayOfSparePart members)

        // *** End programmer edit section *** (IIS.PgBouncerSample.DetailArrayOfSparePart members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type SparePart by index.
        /// </summary>
        /// <summary>
        /// Adds object with type SparePart.
        /// </summary>
        public DetailArrayOfSparePart(IIS.PgBouncerSample.Car fCar) : 
                base(typeof(SparePart), ((ICSSoft.STORMNET.DataObject)(fCar)))
        {
        }
        
        public IIS.PgBouncerSample.SparePart this[int index]
        {
            get
            {
                return ((IIS.PgBouncerSample.SparePart)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.PgBouncerSample.SparePart dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
