//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.PgBouncerSample
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    using ICSSoft.STORMNET.Business.Audit.Objects;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// User report.
    /// </summary>
    // *** Start programmer edit section *** (UserReport CustomAttributes)

    // *** End programmer edit section *** (UserReport CustomAttributes)
    [AutoAltered()]
    [Caption("User report")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("AuditView", new string[] {
            "UserName as \'User name\'",
            "UserEmail as \'User email\'",
            "ReportId as \'Report id\'",
            "ReportTaskStartTime as \'Report task start time\'",
            "Status as \'Status\'",
            "File as \'File\'"})]
    [View("UserReportE", new string[] {
            "UserName",
            "UserEmail",
            "ReportId",
            "ReportTaskStartTime",
            "Status",
            "File"}, Hidden=new string[] {
            "ReportId"})]
    [View("UserReportL", new string[] {
            "UserName",
            "UserEmail",
            "ReportId",
            "ReportTaskStartTime",
            "Status",
            "File"}, Hidden=new string[] {
            "ReportId"})]
    public class UserReport : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields
    {
        
        private string fUserName;
        
        private string fUserEmail;
        
        private System.Guid fReportId;
        
        private System.DateTime fReportTaskStartTime = DateTime.Now;

        private IIS.PgBouncerSample.ReportStatusType fStatus;
        
        private ICSSoft.STORMNET.UserDataTypes.WebFile fFile;
        
        private System.Nullable<System.DateTime> fCreateTime;
        
        private string fCreator;
        
        private System.Nullable<System.DateTime> fEditTime;
        
        private string fEditor;
        
        // *** Start programmer edit section *** (UserReport CustomMembers)

        // *** End programmer edit section *** (UserReport CustomMembers)

        
        /// <summary>
        /// UserName.
        /// </summary>
        // *** Start programmer edit section *** (UserReport.UserName CustomAttributes)

        // *** End programmer edit section *** (UserReport.UserName CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string UserName
        {
            get
            {
                // *** Start programmer edit section *** (UserReport.UserName Get start)

                // *** End programmer edit section *** (UserReport.UserName Get start)
                string result = this.fUserName;
                // *** Start programmer edit section *** (UserReport.UserName Get end)

                // *** End programmer edit section *** (UserReport.UserName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (UserReport.UserName Set start)

                // *** End programmer edit section *** (UserReport.UserName Set start)
                this.fUserName = value;
                // *** Start programmer edit section *** (UserReport.UserName Set end)

                // *** End programmer edit section *** (UserReport.UserName Set end)
            }
        }
        
        /// <summary>
        /// UserEmail.
        /// </summary>
        // *** Start programmer edit section *** (UserReport.UserEmail CustomAttributes)

        // *** End programmer edit section *** (UserReport.UserEmail CustomAttributes)
        [StrLen(255)]
        public virtual string UserEmail
        {
            get
            {
                // *** Start programmer edit section *** (UserReport.UserEmail Get start)

                // *** End programmer edit section *** (UserReport.UserEmail Get start)
                string result = this.fUserEmail;
                // *** Start programmer edit section *** (UserReport.UserEmail Get end)

                // *** End programmer edit section *** (UserReport.UserEmail Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (UserReport.UserEmail Set start)

                // *** End programmer edit section *** (UserReport.UserEmail Set start)
                this.fUserEmail = value;
                // *** Start programmer edit section *** (UserReport.UserEmail Set end)

                // *** End programmer edit section *** (UserReport.UserEmail Set end)
            }
        }
        
        /// <summary>
        /// ReportId.
        /// </summary>
        // *** Start programmer edit section *** (UserReport.ReportId CustomAttributes)

        // *** End programmer edit section *** (UserReport.ReportId CustomAttributes)
        [NotNull()]
        public virtual System.Guid ReportId
        {
            get
            {
                // *** Start programmer edit section *** (UserReport.ReportId Get start)

                // *** End programmer edit section *** (UserReport.ReportId Get start)
                System.Guid result = this.fReportId;
                // *** Start programmer edit section *** (UserReport.ReportId Get end)

                // *** End programmer edit section *** (UserReport.ReportId Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (UserReport.ReportId Set start)

                // *** End programmer edit section *** (UserReport.ReportId Set start)
                this.fReportId = value;
                // *** Start programmer edit section *** (UserReport.ReportId Set end)

                // *** End programmer edit section *** (UserReport.ReportId Set end)
            }
        }
        
        /// <summary>
        /// ReportTaskStartTime.
        /// </summary>
        // *** Start programmer edit section *** (UserReport.ReportTaskStartTime CustomAttributes)

        // *** End programmer edit section *** (UserReport.ReportTaskStartTime CustomAttributes)
        public virtual System.DateTime ReportTaskStartTime
        {
            get
            {
                // *** Start programmer edit section *** (UserReport.ReportTaskStartTime Get start)

                // *** End programmer edit section *** (UserReport.ReportTaskStartTime Get start)
                System.DateTime result = this.fReportTaskStartTime;
                // *** Start programmer edit section *** (UserReport.ReportTaskStartTime Get end)

                // *** End programmer edit section *** (UserReport.ReportTaskStartTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (UserReport.ReportTaskStartTime Set start)

                // *** End programmer edit section *** (UserReport.ReportTaskStartTime Set start)
                this.fReportTaskStartTime = value;
                // *** Start programmer edit section *** (UserReport.ReportTaskStartTime Set end)

                // *** End programmer edit section *** (UserReport.ReportTaskStartTime Set end)
            }
        }
        
        /// <summary>
        /// Status.
        /// </summary>
        // *** Start programmer edit section *** (UserReport.Status CustomAttributes)

        // *** End programmer edit section *** (UserReport.Status CustomAttributes)
        public virtual IIS.PgBouncerSample.ReportStatusType Status
        {
            get
            {
                // *** Start programmer edit section *** (UserReport.Status Get start)

                // *** End programmer edit section *** (UserReport.Status Get start)
                IIS.PgBouncerSample.ReportStatusType result = this.fStatus;
                // *** Start programmer edit section *** (UserReport.Status Get end)

                // *** End programmer edit section *** (UserReport.Status Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (UserReport.Status Set start)

                // *** End programmer edit section *** (UserReport.Status Set start)
                this.fStatus = value;
                // *** Start programmer edit section *** (UserReport.Status Set end)

                // *** End programmer edit section *** (UserReport.Status Set end)
            }
        }
        
        /// <summary>
        /// File.
        /// </summary>
        // *** Start programmer edit section *** (UserReport.File CustomAttributes)

        // *** End programmer edit section *** (UserReport.File CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.WebFile File
        {
            get
            {
                // *** Start programmer edit section *** (UserReport.File Get start)

                // *** End programmer edit section *** (UserReport.File Get start)
                ICSSoft.STORMNET.UserDataTypes.WebFile result = this.fFile;
                // *** Start programmer edit section *** (UserReport.File Get end)

                // *** End programmer edit section *** (UserReport.File Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (UserReport.File Set start)

                // *** End programmer edit section *** (UserReport.File Set start)
                this.fFile = value;
                // *** Start programmer edit section *** (UserReport.File Set end)

                // *** End programmer edit section *** (UserReport.File Set end)
            }
        }
        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (UserReport.CreateTime CustomAttributes)

        // *** End programmer edit section *** (UserReport.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (UserReport.CreateTime Get start)

                // *** End programmer edit section *** (UserReport.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (UserReport.CreateTime Get end)

                // *** End programmer edit section *** (UserReport.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (UserReport.CreateTime Set start)

                // *** End programmer edit section *** (UserReport.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (UserReport.CreateTime Set end)

                // *** End programmer edit section *** (UserReport.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (UserReport.Creator CustomAttributes)

        // *** End programmer edit section *** (UserReport.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (UserReport.Creator Get start)

                // *** End programmer edit section *** (UserReport.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (UserReport.Creator Get end)

                // *** End programmer edit section *** (UserReport.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (UserReport.Creator Set start)

                // *** End programmer edit section *** (UserReport.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (UserReport.Creator Set end)

                // *** End programmer edit section *** (UserReport.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (UserReport.EditTime CustomAttributes)

        // *** End programmer edit section *** (UserReport.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (UserReport.EditTime Get start)

                // *** End programmer edit section *** (UserReport.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (UserReport.EditTime Get end)

                // *** End programmer edit section *** (UserReport.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (UserReport.EditTime Set start)

                // *** End programmer edit section *** (UserReport.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (UserReport.EditTime Set end)

                // *** End programmer edit section *** (UserReport.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (UserReport.Editor CustomAttributes)

        // *** End programmer edit section *** (UserReport.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (UserReport.Editor Get start)

                // *** End programmer edit section *** (UserReport.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (UserReport.Editor Get end)

                // *** End programmer edit section *** (UserReport.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (UserReport.Editor Set start)

                // *** End programmer edit section *** (UserReport.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (UserReport.Editor Set end)

                // *** End programmer edit section *** (UserReport.Editor Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(IIS.PgBouncerSample.UserReport));
                }
            }
            
            /// <summary>
            /// "UserReportE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View UserReportE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("UserReportE", typeof(IIS.PgBouncerSample.UserReport));
                }
            }
            
            /// <summary>
            /// "UserReportL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View UserReportL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("UserReportL", typeof(IIS.PgBouncerSample.UserReport));
                }
            }
        }
        
        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {
            
            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;
            
            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;
            
            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";
            
            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";
            
            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;
            
            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;
            
            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;
            
            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;
            
            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;
            
            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }
}
